services:
  master_psql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${MASTER_USER}"
      POSTGRES_PASSWORD: "${MASTER_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication replicator 0.0.0.0/0 trust"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "${MASTER_PORT}:5432"
    command: |
      postgres
      -c wal_level=logical
      -c hot_standby=on
      -c max_wal_senders=15
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c wal_log_hints=on
      -c shared_preload_libraries='pg_partman_bgw'
    volumes:
      - pgdata:/var/lib/postgresql/data #Data Volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s

volumes:
  pgdata:
    driver: local
